'use strict';
// PiPulse's glossary: every term the pages mark with UI.term(). The Bracket kit already defines the
// general ones (cpu, cores, load, memory, swap, soc-temp, throttling, under-voltage, disk, network,
// uptime, session, lan-only, …); entries here with the same key replace the kit's. Text is plain:
// blank lines split paragraphs, **bold**, and [[key]] or [[key|label]] link another term.
Glossary.add({
  // ---- a Pi's health --------------------------------------------------------------------------
  health: { term: 'Health', short: 'One-word summary of this Pi: All good, Attention, Problem or Offline.',
    long: 'Health rolls up the Pi\'s active [[alert|alerts]]. **Attention** means a warning (worth a look soon), **Problem** means something critical (act now), **Offline** means the hub has not heard from the Pi. The line under it names the alerts.',
    healthy: 'All good.', fix: 'Open the Pi and read its alerts; each one names the measurement that tripped, and that measurement has its own explanation here.', related: ['alert', 'offline', 'sustain'] },
  alert: { term: 'Alert', short: 'A problem the hub noticed: raised when it has lasted a while, cleared when it goes away.',
    long: 'Each alert compares a measurement with a threshold from Settings (for example memory above 90%). To stop short spikes from alerting, most must last the [[sustain|problem-must-last]] time first; offline, under-voltage, throttling and a read-only disk alert at once.\n\nEvery alert is written to Events twice: when it is raised and when it clears.',
    related: ['sustain', 'health', 'offline'] },
  sustain: { term: 'Problem must last', short: 'How long a problem has to continue before it becomes an alert.',
    long: 'A Pi doing a big job (installing updates, a backup) can run hot or busy for a minute without anything being wrong. Waiting this long before alerting keeps the dashboard and Events free of noise.',
    healthy: '60 seconds is a good default.', related: ['alert'] },
  offline: { term: 'Offline', short: 'The hub has not received a report from this Pi for a while.',
    long: 'Every Pi\'s [[client]] reports every few seconds. When reports stop for longer than "offline after" in Settings, the Pi is marked offline. The cards then show the last values the hub received, faded.\n\nThe Pi may be switched off, rebooting, off the network, or its client may have stopped.',
    fix: 'Check the Pi has power and network. If it answers SSH, run "sudo pipulse" on it and choose "Test the connection to the hub".', related: ['client', 'link-latency'] },
  'link-latency': { term: 'Link latency', short: 'How long one report takes to reach the hub and get an answer, in milliseconds.',
    long: 'Measured by the [[client]] on every report over the [[encrypted-link]]. On a home network it is usually a few milliseconds; Wi-Fi adds more and jumps around.',
    healthy: 'Under about 20 ms on wired Ethernet, under 100 ms on Wi-Fi.', fix: 'High or jumpy latency points at weak Wi-Fi or a busy network. A Pi that is overloaded also answers slowly.', related: ['offline', 'network'] },
  'disk-writes': { term: 'Disk writes', short: 'How fast the Pi is writing to its disk, and how much since it started.',
    long: 'SD cards wear out after a limited amount of writing. Logs, databases and swap are the usual heavy writers. A USB SSD handles writing far better than an SD card.',
    healthy: 'A few hundred KB/s or less most of the time.', fix: 'Find the busy writer (often logging or swapping), make it log less, or move it to an SSD. The Disk-write warning in Settings can alert you.', related: ['disk', 'swap', 'read-only'] },
  'read-only': { term: 'Read-only filesystem', short: 'The Pi\'s main disk has stopped accepting writes.',
    long: 'Linux switches a disk to read-only when it detects errors, to protect what is left. On a Raspberry Pi this almost always means the SD card is failing or was corrupted by a power cut. Programs that need to save anything will fail.',
    healthy: 'Read-write.', fix: 'Back up what you can now, then replace the SD card (an SSD is better). Check the power supply too: [[under-voltage]] corrupts cards.', related: ['disk-writes', 'under-voltage'] },
  reboot: { term: 'Reboot detection', short: 'PiPulse notices when a Pi has restarted, and whether the dashboard asked it to.',
    long: 'Each boot has a unique ID. When it changes, the hub logs "rebooted from the dashboard" if you pressed Reboot, and "rebooted, not from PiPulse" otherwise: a power cut, a crash, someone pulling the plug, or a reboot you started yourself.',
    fix: 'Repeated unexpected reboots usually mean power trouble ([[under-voltage]]) or overheating ([[soc-temp]]).', related: ['uptime', 'under-voltage'] },

  // ---- hub, client, encryption ------------------------------------------------------------------
  hub: { term: 'Hub', short: 'The PiPulse program that holds the dashboard, the logs, the settings and the alerts.',
    long: 'It runs on one Pi (here: aether) and every [[client]] reports to it. It keeps recent history in its database and mirrors it to the NAS.', related: ['client', 'encrypted-link'] },
  client: { term: 'Client', short: 'The small PiPulse program on each Pi that reports to the hub.',
    long: 'It reads the Pi\'s numbers every few seconds and sends them over the [[encrypted-link]]. It also carries out what you ask from the dashboard: limits, restarts, updates. It is capped at 10% CPU and 48 MB of memory so the monitor can never be what slows a Pi down.\n\nOn the Pi, "sudo pipulse" opens its menu.',
    related: ['hub', 'client-version'] },
  'client-version': { term: 'Client version', short: 'Which version of PiPulse the Pi\'s client runs.',
    long: 'Clients install from the hub, so after the hub is updated each client shows "update" until you press Update (or Update all Pis). It updates over the encrypted link and restarts itself.', related: ['client', 'hub'] },
  'encrypted-link': { term: 'Encrypted link', short: 'Reports travel from each Pi to the hub over HTTPS on port 8751.',
    long: 'The hub makes its own certificate; every client checks its [[fingerprint]] before sending anything, so nothing else on the network can read the reports or pretend to be the hub. No certificate authority or paid certificate is involved.', related: ['fingerprint', 'token'] },
  fingerprint: { term: 'Certificate fingerprint', short: 'A unique code that identifies the hub\'s certificate.',
    long: 'Each client remembers ("pins") this code when it is installed and refuses to talk to anything that shows a different one. If you move the hub to a new Pi, copy its data folder (with hub-cert.pem and hub-key.pem) so the fingerprint stays the same.', related: ['encrypted-link'] },
  token: { term: 'Token', short: 'The shared secret a client uses to prove it belongs to this hub.',
    long: 'It is part of the Add a Pi command, which is why only admins can see that page. It only ever travels over the [[encrypted-link]].', related: ['encrypted-link'] },

  // ---- services, processes, limits --------------------------------------------------------------
  service: { term: 'Service', short: 'A program systemd starts and keeps running in the background, like medialedger or ssh.',
    long: 'Services are what PiPulse can limit, restart and watch. Their CPU and memory are measured as a group, so a service with many processes shows as one line.', related: ['tasks', 'cpu-cap', 'memory-cap', 'watchdog'] },
  tasks: { term: 'Tasks', short: 'How many processes and threads the service is running.', related: ['service', 'process'] },
  process: { term: 'Process', short: 'One running program. A service can be made of several.',
    long: 'The list shows the busiest processes and the biggest memory users. [[rss|RAM]] is the memory the process holds right now; [[nice]] is its priority.', related: ['rss', 'nice', 'service'] },
  rss: { term: 'Resident memory (RSS)', short: 'The RAM a process is actually holding right now.', related: ['memory', 'process'] },
  nice: { term: 'Nice', short: 'A process\'s CPU priority: higher numbers step aside for others.',
    long: '0 is normal, 19 is the most polite, negative numbers push ahead. Changing it from the dashboard lasts until the process restarts; for a permanent change give the service a [[cpu-weight|priority]] instead.', related: ['cpu-weight', 'process'] },
  'cpu-cap': { term: 'CPU cap', short: 'The most CPU a service may use, counted in cores.',
    long: 'Enforced by systemd (CPUQuota). "0.5 cores" means the service can never use more than half of one core, however hard it tries, so the rest of the Pi stays responsive. It survives reboots and does not change the program.',
    healthy: 'Only on services that hog the Pi.', related: ['memory-cap', 'cpu-weight', 'guard-rule', 'cores'] },
  'memory-cap': { term: 'Memory cap', short: 'The most RAM a service may use.',
    long: 'Near 90% of the cap the service is slowed down and made to give memory back (MemoryHigh). Past the cap, systemd kills it and restarts it (MemoryMax), instead of the whole Pi running out of memory and freezing.', related: ['cpu-cap', 'memory', 'oom'] },
  'cpu-weight': { term: 'Priority (CPU weight)', short: 'How much of a busy CPU a service gets compared with others.',
    long: 'Only matters when the CPU is fully busy: a service with weight 200 then gets twice the share of one with the default 100. Background (20) and Low (50) are good for batch jobs that should never get in the way.', related: ['cpu-cap', 'nice'] },
  oom: { term: 'Out of memory (OOM) killer', short: 'The Linux safety valve that kills a program when memory runs out.',
    long: 'When RAM and [[swap]] are both exhausted, the kernel picks a large process and ends it. It keeps the machine alive but may kill the wrong program. A [[memory-cap]] on the likely culprit makes sure it is the one that restarts.', related: ['memory', 'memory-cap'] },
  watchdog: { term: 'Watched service', short: 'A service PiPulse checks is still running, with an alert if it stops.',
    long: 'The client asks systemd for its state every 15 seconds. A stopped or failed watched service raises a critical alert. With [[auto-restart]] on, the hub also restarts it.', related: ['auto-restart', 'service'] },
  'auto-restart': { term: 'Auto-restart', short: 'The hub restarts a watched service when it stops.',
    long: 'At most once every 2 minutes and 3 times an hour. After the third try it gives up and logs that it did, because a service that keeps dying needs a person to look at why.', related: ['watchdog'] },
  'guard-rule': { term: 'Guard rule', short: 'Automatic protection: a service that stays over a limit gets capped.',
    long: 'For example "any service above 150% CPU for 5 minutes gets capped at 1 core". A rule fires once per service, logs an event, keeps the service\'s other limits, and never touches SSH, systemd\'s core services or PiPulse. Clear the cap from the Services tab when you are done.', related: ['cpu-cap', 'memory-cap'] },

  // ---- OS updates, power ---------------------------------------------------------------------------
  'os-updates': { term: 'OS updates', short: 'Newer versions of the Pi\'s installed software, waiting to be installed.',
    long: 'The client checks with apt every 6 hours. [[security-updates|Security updates]] fix known vulnerabilities and are the ones to install promptly. Installing runs apt upgrade in the background, outside the client\'s CPU cap.', related: ['security-updates', 'reboot-required'] },
  'security-updates': { term: 'Security updates', short: 'Updates that fix known security problems.', healthy: 'None waiting.', fix: 'Press Install OS updates on that Pi.', related: ['os-updates'] },
  'reboot-required': { term: 'Reboot required', short: 'An update (usually the kernel) only takes effect after a restart.', fix: 'Reboot the Pi when it suits you.', related: ['os-updates', 'reboot'] },

  // ---- hub storage -------------------------------------------------------------------------------------
  mirror: { term: 'NAS mirror', short: 'A copy of the hub\'s database saved to the NAS every hour.',
    long: 'The live database stays on the Pi (a database over a network share can corrupt), and a consistent snapshot is copied to the NAS so the NAS always has a recent copy you can open.', related: ['archive', 'backup'] },
  archive: { term: 'Archive', short: 'Data older than the history limits, moved to the NAS as daily files instead of deleted.',
    long: 'One compressed CSV per day per table, under archive/ in the NAS logs folder, so the NAS keeps everything forever while the Pi stays small. If the NAS is away the hub holds the data for up to a week until it is back.', related: ['retention', 'mirror'] },
  backup: { term: 'Backup', short: 'A nightly copy of the database plus the hub\'s certificate and key.',
    long: 'Restoring one ("sudo pipulse-hub restore <file>" on the hub Pi) brings back settings, Pis, history and events, and every client keeps trusting the hub because the certificate comes back too. The newest 30 are kept.', related: ['mirror', 'fingerprint'] },
  retention: { term: 'History limits', short: 'How long the hub keeps detailed data, hourly averages and events on the Pi.',
    long: 'Full detail (every report) is kept for days; hourly averages for a year. With the [[archive]] on, anything older moves to the NAS rather than being deleted.', related: ['archive'] },
});
